version: '3.8'

networks:
  app-network:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ../symfony:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8-service
      - mysql8-service
    networks:
      - app-network

  # php
  php8-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php8-container
    ports:
      - "9000:9000"
    volumes:
      - ../symfony:/var/www/symfony
    networks:
      - app-network

  # mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped # always restart unless stopped manually
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    networks:
      - app-network

  # node
  node-service:
    build:
      context: ../react-app
      dockerfile: ../docker/node/Dockerfile
    container_name: node-container
    ports:
      - "3000:3000"
    volumes:
      - ../react-app/src:/app/src
    networks:
      - app-network